# Generated by Django 4.2.5 on 2023-09-29 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_tags_category_slug_product_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0002_rename_timestamp_interest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='message',
            field=models.TextField(default="I'm interested in your product. Please provide more details."),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('user', 'product')},
        ),
    ]
