# Generated by Django 4.2.5 on 2023-09-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='estimated_delivery_time',
        ),
    ]
