# Generated by Django 4.2.5 on 2023-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_estimated_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='product_images/default_product_image.png', upload_to='product_images/'),
        ),
    ]
